version: '3.8'

services:
  php-apache:
    build: .
    container_name: php_api_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'person'
      MYSQL_USER: 'machine'
      MYSQL_PASSWORD: 'J&0Ra6D1%#0PSz'
      MYSQL_ROOT_PASSWORD: '1623'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: